= Parameters

The parent key for all of the following parameters is `crossplane`.

== `namespace`

[horizontal]
type:: string
default:: `syn-crossplane`

The namespace in which to deploy Crossplane.

== `providers`

[horizontal]
type:: dictionary
default:: undefined

A dictionary holding the https://crossplane.github.io/docs/v1.7/concepts/providers.html[Crossplane providers] to be installed.
The keys of the dict are used as names for the Provider objects.

== `monitoring.enabled`

[horizontal]
type:: bool
default:: `true`

If monitoring should be enabled for this component.
Requires the https://github.com/prometheus-operator/prometheus-operator[Prometheus Operator] to be installed.

== `monitoring.prometheus_rule_labels`

[horizontal]
type:: dict
default:: `{"prometheus":"platform"}`

Labels to set on the alert rule configuration.
Can be used to ensure prometheus-operator picks up the `PrometheusRule` object by setting appropriate labels.

== `helmValues`

[horizontal]
type:: dict

Values to configure the Helm chart.
See https://github.com/crossplane/crossplane/tree/master/cluster/charts/crossplane[the docs] for available parameters.

== Example

[source,yaml]
----
parameters:
  crossplane:
    images:
      crossplane:
        image: mymirror.io/crossplane/crossplane
    providers:
      helm:
        package: crossplane/provider-helm:v0.3.5
    monitoring:
      enabled: false
    helmValues:
      resourcesCrossplane:
        limits:
          cpu: 2000m
        requests:
          cpu: 1000m
----
